eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost}:8761/eureka
spring:
  application:
    name: auth
    
server:
  port: 7011
  
---
spring:
  data:
    mongodb:
      uri: mongodb://oguz:123456@localhost:27019/jwt?authMechanism=SCRAM-SHA-256&authSource=admin
