eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost}:8761/eureka
server:
  port: 9000
  
spring:
  application:
    name: auth-server
  security:
    oauth2:
      authorizationserver:
        client:
          client:
            registration:
              clientId: "client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/spring"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/logged-out"  
              scopes:
                - "openid"
                - "profile"
                - "user.read"
                - "user.write"
            require-authorization-consent: false
            require-proof-key: false
  
---
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:root}:${MONGODB_PASS:123456}@${MONGODB_HOST:localhost}:27017/authorization?authMechanism=SCRAM-SHA-256&authSource=admin
