eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost}:8761/eureka
server:
  port: 9000
  
spring:
  application:
    name: auth-server
  
---
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:root}:${MONGODB_PASS:123456}@${MONGODB_HOST:localhost}:27017/auth-server?authMechanism=SCRAM-SHA-256&authSource=admin
