eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761
spring:
  application:
    name: discovery
