eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost}:8761/eureka
    register-with-eureka: false
  instance:
    hostname: localhost
    preferIpAddress: true
server:
  port: 8080
spring:
  application:
    name: gateway
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379
  
resilience4j:
  circuitbreaker:
    instances:
      resourceServer:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
  timelimiter:
    configs:
     resourceServer:
         timeoutDuration: 20s

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER_URL:http://localhost}:9411/api/v2/spans
